### ISSUE TITLE
#4

### ISSUE THREAD

**Issue by pennyjs** [y-vm/y-vm.github.io#4]

**Comment by 2892** [comment]
```
set name "joe"
get name
```

**Comment by 2892** [comment]
**namespace** `set user:1 "joe"`

**Comment by 2892** [comment]
`k` and `v`
`key` can be any string, `value` also strings

**Comment by 2892** [comment]
**Strings**

```
set name "nhn"
append name " kr"
get name
```

**Comment by 2892** [comment]
`getrange name 0 3`

**Comment by 2892** [comment]
```
getset name nhn
mset name nhn code moon
mget name code
```

**Comment by 2892** [comment]
```
set code 200
incr code
get code
```

**Comment by 2892** [comment]
*expire*

```
setex color 20 red
```

**Comment by 2892** [comment]
```
setnx name hello
msetnx name hello code 200
```

**Comment by 2892** [comment]
```
strlen name
```

**Comment by 2892** [comment]
**Lists**

```
lpush colors red
lpush colors blue green orange
```

**Comment by 2892** [comment]
```
rpush colors black
lpushx names white
```

**Comment by 2892** [comment]
```
lpop colors
rpop colors
```

**Comment by 2892** [comment]
`linsert beofre`
`linsert after`

**Comment by 2892** [comment]
```
lindex colors 3
lset colors 2 red
```

**Comment by 2892** [comment]
```
ltrim colors 0 3
```

**Comment by 2892** [comment]
**configuration**

```
redis-server redis.conf
```

**Comment by 2892** [comment]
```
daemonize yes
port 9908
loglevel debug
logfile stdout
save 300 5
requirepass pass
```

```
redis-cli -p 9908
auth pass
```

**Comment by 2892** [comment]
```
key *
```

**Comment by 2892** [comment]
```
slaveof localhost 7890
slave-read-only yes
```

**Comment by 2892** [comment]
```
sudo apt-get install mariadb-server libmariadbclient-dev
```

**Comment by 2892** [comment]
```
production:
  encoding: utf8
  adapter: mysql2
  host: localhost
  pool: 5
  username: <%= ENV['MARIADB_USERNAME'] %>
  password: <%= ENV['MARIADB_PASSWORD'] %>
  database: <%= ENV['MARIADB_DATABASE'] %>
```
